---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(lubridate)
library(dplyr)

library(p8105.datasets)
```

```{r, include=FALSE}
set.seed(1)

data(ny_noaa)
ny_noaa <- ny_noaa %>% 
  mutate(
  year = lubridate::year(date),
  month = lubridate::month(date),
  day = lubridate::day(date),
  prcp = prcp/10,
  tmin = as.numeric(tmin)/10,
  tmax = as.numeric(tmax)/10
  ) %>% 
  rename(tmax_ºC = tmax, tmin_ºC = tmin, prcp_mm = prcp , snow_mm = snow, snwd_mm = snwd) %>% 
  select(id, year, month, day, prcp_mm, snow_mm, snwd_mm, tmax_ºC, tmin_ºC)

ny_noaa %>% 
  sample_n(1000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Scatter plot

#### The average minimum temperature of each month over years

```{r scatterplot,warning=FALSE}

ny_noaa %>% 
  mutate(
    month = recode_factor(month,
          "01" = "January",
          "02" = "February",
          "03" = "March",
          "04" = "April",
          "05" = "May",
          "06" = "June",
          "07" = "July",
          "08" = "August",
          "09" = "September",
          "10" = "October",
          "11" = "November",
          "12" = "December"),
    year = as.numeric(year)) %>%
 
  group_by(id, year, month) %>%
  summarize(mean_tmin = mean(tmin_ºC)) %>% 
  plot_ly(x = ~year, y = ~mean_tmin, type = "scatter", mode = "markers", alpha = 0.5,color = ~month)

```

#### The relationship between the avarage snow fall and the average snow depth among different years

```{r }
ny_noaa %>% 
  mutate(
    
    year = as.numeric(year)) %>%
 
  group_by(id, year) %>%
  summarize(mean_snwf = mean(snow_mm), mean_snwd = mean(snwd_mm)) %>% 
  plot_ly(x = ~mean_snwf, y = ~mean_snwd, type = "scatter", mode = "markers", alpha = 0.5,color = ~year)

```


### Box Plot

#### Distribution of the average minimum temperature among diffrent weather stations over years

```{r boxplot, warning=FALSE}
ny_noaa  %>%
   mutate(
    year = as.factor(year)) %>%
  group_by(id, year) %>%
  summarize(avg_tmin = mean(tmin_ºC)) %>%
  plot_ly(x = ~year, y = ~avg_tmin, type = "box", 
          alpha = .5,color = ~year, colors = "viridis")
```

### Bar Chart

#### Number of records with value collected in each year

```{r barchart, warning=FALSE}
ny_noaa %>% 
  drop_na(year) %>%
  filter(prcp_mm != "NA" | snow_mm != "NA" | snwd_mm != "NA" | tmax_ºC != "NA" | tmin_ºC != "NA") %>%
  mutate(
    year = as.factor(year)) %>%
  count(year) %>% 
  mutate(year = fct_reorder(year, n)) %>% 
  plot_ly(x = ~year, y = ~n, color = ~year, type = "bar")
```

